Objective value
2.22963

Eta
[7, 4]

Ambulance located
[7.0, 4.0]

Ambulance location
['equal to eta', 'equal to eta']

Scnenario
[[0, 0], [0, 0], [0, 1], [0, 0], [1, 1], [2, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 3], [0, 0], [0, 2], [0, 0], [1, 0], [0, 0], [1, 1], [1, 0], [0, 0]]
[[0, 0], [0, 0], [2, 0], [0, 0], [0, 0], [0, 0], [0, 1], [1, 2], [0, 0], [0, 0], [0, 0], [2, 1], [1, 0], [0, 0], [0, 0], [0, 0], [1, 3], [0, 0], [0, 0], [0, 0]]
[[1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [1, 2]]
[[0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
[[3, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [0, 0], [1, 2], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 1], [2, 2], [0, 0], [0, 0], [0, 1], [1, 0], [0, 1], [1, 0]]
[[0, 2], [0, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [0, 3], [0, 0], [0, 1], [0, 0], [0, 2], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 1], [1, 2], [1, 2], [0, 0], [0, 0], [0, 0], [0, 2], [1, 0], [0, 0], [1, 1]]
[[0, 0], [2, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 2], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0]]
[[0, 0], [2, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [1, 1], [0, 2], [0, 0], [0, 0], [0, 0], [0, 3], [0, 1], [1, 0], [2, 0], [0, 0], [0, 1], [0, 2]]
[[0, 0], [0, 0], [3, 0], [1, 0], [0, 3], [1, 0], [0, 0], [0, 1], [0, 0], [1, 0], [1, 1], [0, 0], [0, 1], [0, 0], [0, 2], [0, 0], [0, 0], [0, 3], [0, 2], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [3, 0], [0, 1], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0]]

Dispatches
[[0, 0], [0, 0], [0, 1], [0, 0], [1, 1], [2, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 1], [0, 1], [0, 0]]
[[0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0], [2, 1], [0, 1], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0]]
[[1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1]]
[[0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
[[1, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [0, 0], [1, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [1, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 1], [2, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 1], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 1], [1, 1], [1, 2], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0]]
[[0, 0], [2, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [2, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [1, 0], [1, 0], [0, 0], [0, 1], [0, 0]]
[[0, 0], [0, 0], [2, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [1, 0], [1, 1], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [3, 0], [0, 1], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0]]

Coverage
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['full', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'partial', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'partial', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['partial', 'partial']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['partial', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'partial', 'null'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'partial', 'null', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['full', 'no accident'], ['no accident', 'full'], ['full', 'no accident']]
[['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['partial', 'null', 'partial'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'partial', 'null', 'null']]
[['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['full', 'partial', 'null', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'full'], ['full', 'no accident'], ['partial', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'null']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident'], ['full', 'no accident'], ['no accident', 'null'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'partial'], ['full', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident']]

