Objective value
4.2125

Eta
[7, 4]

Ambulance located
[4, 4]

Ambulance location
['less than eta', 'equal to eta']

Scnenario
[[3, 0], [0, 0], [1, 0], [0, 0], [0, 3], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [3, 0]]
[[0, 0], [0, 1], [1, 0], [2, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [2, 0], [2, 1], [0, 0], [0, 0], [1, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 1], [0, 0], [0, 0], [1, 0], [1, 0], [1, 0], [0, 0], [1, 0], [2, 0], [1, 0], [1, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 1], [0, 2], [2, 0], [0, 3], [1, 0], [1, 0], [0, 2], [0, 1], [0, 0], [0, 0], [0, 1], [2, 0], [1, 0], [0, 0], [0, 1], [0, 0], [1, 0]]
[[0, 1], [0, 2], [0, 2], [1, 1], [0, 0], [2, 0], [0, 1], [1, 1], [0, 0], [0, 0], [0, 1], [2, 0], [0, 0], [0, 0], [1, 0], [0, 2], [0, 1], [0, 0], [0, 0], [1, 2]]
[[0, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [2, 1], [0, 0], [0, 1], [0, 0], [0, 2], [0, 0], [1, 0]]
[[0, 2], [0, 0], [0, 0], [0, 2], [0, 0], [0, 1], [0, 0], [0, 1], [1, 1], [0, 0], [2, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 2], [0, 0], [1, 3], [0, 0]]
[[1, 2], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [3, 0], [0, 0], [0, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 1], [0, 0], [2, 0], [0, 1], [0, 0], [0, 0], [1, 0], [2, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [2, 0], [1, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [1, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 1], [1, 2], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [2, 0], [0, 0], [2, 0], [2, 0], [0, 0], [0, 0], [0, 1], [2, 1], [0, 0], [0, 0], [1, 1], [0, 1], [2, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0]]

Dispatches
[[3, 0], [0, 0], [1, 0], [0, 0], [0, 1], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [1, 0]]
[[0, 0], [0, 1], [1, 0], [2, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [2, 0], [1, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 1], [0, 0], [0, 0], [1, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [1, 0], [1, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 1], [2, 0], [1, 0], [0, 0], [0, 1], [0, 0], [1, 0]]
[[0, 1], [0, 0], [0, 0], [1, 0], [0, 0], [2, 0], [0, 1], [1, 1], [0, 0], [0, 0], [0, 1], [2, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [0, 0], [0, 2], [0, 0], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 1], [1, 0], [0, 0], [2, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0]]
[[1, 1], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 1], [0, 0], [2, 0], [0, 1], [0, 0], [0, 0], [1, 0], [2, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [2, 0], [1, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [1, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 1], [1, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [2, 0], [0, 0], [0, 0], [0, 1], [1, 0], [0, 0], [0, 0], [1, 0], [0, 1], [2, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0]]

Coverage
[['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'partial'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['partial', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['null', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['null', 'no accident'], ['full', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'null'], ['partial', 'no accident'], ['no accident', 'null'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'null'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident']]
[['no accident', 'full'], ['no accident', 'null'], ['no accident', 'null'], ['full', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'null'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['null', 'null']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'null'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident']]
[['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['full', 'null'], ['no accident', 'no accident']]
[['full', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'full'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['null', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['partial', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'null'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident']]

