Objective value
4.81975

Eta
[7, 4]

Ambulance located
[7, 4]

Ambulance location
['equal to eta', 'equal to eta']

Scnenario
[[1, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [0, 1], [2, 0], [1, 0], [0, 0], [1, 3], [2, 0], [1, 2], [0, 0], [2, 0], [3, 1]]
[[0, 0], [0, 2], [0, 0], [0, 0], [2, 0], [1, 1], [0, 1], [1, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [2, 0], [0, 0], [1, 0]]
[[2, 2], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [1, 0], [0, 1], [1, 1], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1], [0, 2]]
[[1, 0], [0, 1], [0, 0], [0, 0], [3, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [2, 0], [2, 0], [3, 0], [0, 0], [0, 1], [0, 0], [0, 0], [2, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [1, 0], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [2, 2], [0, 0], [1, 0], [0, 1], [1, 0], [0, 0], [0, 1], [0, 2]]
[[0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [2, 2], [0, 0], [3, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [1, 0], [0, 0], [0, 0], [2, 0], [0, 0], [2, 1], [0, 0], [2, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [2, 0], [0, 2], [0, 1], [0, 0], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 1], [0, 0], [0, 1], [0, 2], [0, 2], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [2, 0], [0, 1], [3, 0], [0, 0], [2, 0]]
[[1, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 1], [1, 0], [0, 0], [1, 2], [0, 0], [0, 0]]
[[0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [0, 1], [2, 1], [0, 0], [0, 3], [0, 0], [1, 0], [0, 2], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0]]

Dispatches
[[1, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [0, 1], [1, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [1, 0], [1, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [1, 1], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [2, 0], [0, 0], [1, 0]]
[[2, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [1, 0], [0, 1], [1, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0]]
[[1, 0], [0, 1], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [2, 0], [1, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [1, 0], [0, 1], [1, 0], [0, 0], [0, 1], [0, 0]]
[[0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [2, 0], [0, 0], [3, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [2, 0], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [1, 0], [0, 0], [0, 0], [2, 0], [0, 0], [1, 1], [0, 0], [2, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0], [0, 1], [1, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [2, 0], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0], [0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [2, 0], [0, 1], [1, 0], [0, 0], [1, 0]]
[[1, 0], [0, 0], [0, 0], [0, 2], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 1], [1, 0], [0, 0], [1, 1], [0, 0], [0, 0]]
[[0, 0], [0, 1], [0, 0], [1, 0], [0, 0], [0, 1], [2, 0], [0, 0], [0, 1], [0, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [2, 0], [0, 0]]

Coverage
[['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['partial', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['null', 'null'], ['partial', 'no accident'], ['null', 'partial'], ['no accident', 'no accident'], ['partial', 'no accident'], ['partial', 'null']]
[['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['full', 'full'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident']]
[['full', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['full', 'null'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'null']]
[['full', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['partial', 'no accident'], ['null', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['null', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'null']]
[['no accident', 'full'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'null'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['partial', 'full'], ['no accident', 'no accident'], ['full', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['full', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'partial'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'null'], ['no accident', 'partial'], ['no accident', 'null'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['partial', 'no accident'], ['no accident', 'no accident'], ['partial', 'no accident']]
[['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'full'], ['full', 'no accident'], ['no accident', 'no accident'], ['full', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident']]
[['no accident', 'no accident'], ['no accident', 'full'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident'], ['no accident', 'full'], ['full', 'null'], ['no accident', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'partial'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['no accident', 'no accident'], ['full', 'no accident'], ['no accident', 'no accident']]

